### ISSUE TITLE
Service not remove from Eureka server when stop docker container

### ISSUE THREAD

**Issue by hosseinhelali** [anilallewar/microservices-basics-spring-boot#15]
when service container stop by user.service not remove from eureka server
after search in internet i found this post
[https://stackoverflow.com/questions/31836498/sigterm-not-received-by-java-process-using-docker-stop-and-the-official-java-i](url)
and i solved this problem by change entry point in docker file.

```
#-----------------------------------------------------------------------------------------------------
# User Service
#-----------------------------------------------------------------------------------------------------
FROM openjdk:8u121-jdk-alpine

MAINTAINER Anil Allewar <anilallewar@yahoo.co.in>

# Keep consistent with build.gradle 
ENV APP_JAR_NAME basic-user-webservice
ENV APP_JAR_VERSION 0.0.1

# Install curl
RUN apk --update add curl bash && \
	rm -rf /var/cache/apk/*
	
RUN mkdir /app

ADD ${APP_JAR_NAME}-${APP_JAR_VERSION}.jar /app/service.jar 
ADD run.sh /app/
RUN chmod +x /app/run.sh 

WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/urandom",  "-Dspring.profiles.active=docker",  "-jar",  "/app/service.jar"]
```

**Comment by anilallewar** [comment]
Thanks for the finding; yes currently the Java process was run as child of the shell.

Fixed this by adding "exec" to the shell launching the java command rather than in DockerFile. We need the shell script to launch the process so that we can also manipulate the CMD in case of docker orchestration engine like kubernetes.

Please see the contents in "docker-orchestration/k8s/manifests" to understand how we change the ENTRYPOINT while running the kubernetes dependency graph.

**Comment by hosseinhelali** [comment]
Thanks
