### ISSUE TITLE
Issue when build webservice-registry. You can fix it?

### ISSUE THREAD

**Issue by thuansystemit** [anilallewar/microservices-basics-spring-boot#2]
Hi all,
I'm building webservice-registry. but i have a problem with webservice-registry.
I'm using gradle version 4.2 and java 8.
Please tell me about. How to fix it.
Thanks.

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':compileJava' property 'classpath' during up-to-date check.
> java.lang.UnsupportedOperationException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.it

**Comment by anilallewar** [comment]
I think the problem is with the gradle version you have on the system and what is supported by the plugins used in the application.

Can you try building with the grade wrapper included with the project? You can simply run the build-all-projects.sh" shell script at the root folder and that would run the gradle wrapper build for all the service projects.

Thanks,
Anil
