### ISSUE TITLE
Invalid access token: while trying to access task-service

### ISSUE THREAD

**Issue by muhmadtabrez** [anilallewar/microservices-basics-spring-boot#3]
Hi,

  I am trying to run this example application i have set up everything and its working fine but there are some exception is task-service. 
 
  when i am trying to access http://localhost:8765/task-service i am getting following error 

<oauth>
<error_description>
Invalid access token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDcxNjUwNzIsInVzZXJfbmFtZSI6ImFuaWwiLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImp0aSI6ImVhZGIxM2ViLWRlOGYtNDk3Mi04ZGJlLTBhYmMzNzE0OTZkYiIsImNsaWVudF9pZCI6ImFjbWUiLCJzY29wZSI6WyJvcGVuaWQiXX0.XkcrzfnoxkJCsbZFA3DvPrwLyRtURXQqu8iQW9RJaeE6cyGmsLYPLEwDBaUlfiIkuSdMjZJLtIOfG9B9rP7qD-JlqQu27t5EUjEY6SpgVR7vg2Wm-RxP69nqQatEmJ72U5h17JCHEX_buQNtmnzNRhzIrN0t2pYjjJzFTeZYtzG0vIXsDpPpi3ASTpdT17wWM6EvEiU4vIloLuqbNUEOS7JbcoMDOzizHMD9Bc1SEJ7wbGI8Esib7FvcAkVf_MKwobeWWRoeLeP96g5FsnpIJVhLfJ3HHJAtofmMXpfiP9_K6FDoaXPddeaFG2SZY9Uo2YkeJu_OsTq4fcaXTUqvbQ
</error_description>
<error>invalid_token</error>
</oauth>

**Comment by HJK181** [comment]
Same for me, can you please help?

**Comment by anilallewar** [comment]
It means that the access token you acquired earlier has expired (Spring default access token validity is 12 hours). There are 2 options available

1. Open the app in an InCognito Window in chrome. Since Chrome doesn't store local storage in InCognito mode, you will be prompted for user name/password and will be able to generate a new token.
2. Click on the "Refresh Token" link in the menu for the current app. This will generate a new access token based on the refresh token. Note that the default refresh token validity is 30 days.

**Comment by HJK181** [comment]
I already tried both of the suggested, without success. 

I also tried to debug it and found that when requesting the task-service, the Spring DefalutTokenServices loads the InMemoryTokenStore in the field `tokenStore` where on request to the user-service the `JdbcTokenStore` get's loaded.

I assume there is some missing configuration on the task-service but I'm not that familiar with all that Spring magic yet. Do you have any idea whats going wrong?

**Comment by PatrickHuetter** [comment]
Same problem here.

**Comment by anilallewar** [comment]
Moved the Web portal out - replaced with Swagger API at the API gateway level.
