### ISSUE TITLE
Question: Should I use one config-server and one service-registry for each app?

### ISSUE THREAD

**Issue by helder-jaspion** [anilallewar/microservices-basics-spring-boot#8]
I know this project is an example but in real world should I have one config-server and one service-registry for each application?
Or should I have a global config server and a global service-registry which all the services of all projects will use?

**Comment by anarayn** [comment]
Did you find the answer for this? I also have same thought and looking for answer.

**Comment by anilallewar** [comment]
Sorry, just wasn't keeping track of this..

In the real world you would typically have a single config-server and 1 (or more) service registry for all the services in your application.

Typically in high availability systems you want more than 1 service registry so that we have redundancy if one of them fails.
